"""
Django settings for Inventory project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%m#9ig&=05^)h8xv(1@ag76v7ptx44_ur9xh99p+(nwgxecgbl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'invent.apps.InventConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'invent.context_processors.pending_requests_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'Inventory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration for Password Reset
# For development: Prints emails to the console
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production/real email sending, uncomment and configure these:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# <-- REPLACE with your email provider's SMTP host (e.g., 'smtp.gmail.com')
EMAIL_HOST = 'smtp.gmail.com'
# <-- REPLACE if your provider uses a different port (e.g., 465 for SSL)
EMAIL_PORT = 587
# <-- Set to True or False based on your provider (or EMAIL_USE_SSL = True)
EMAIL_USE_TLS = True
# <-- REPLACE with your actual email address
EMAIL_HOST_USER = 'brianobanda08@gmail.com'
# <-- REPLACE with your actual email password or an App Password
EMAIL_HOST_PASSWORD = 'nqkg yewg gxwq anji'
# <-- REPLACE with your actual email address (sender)
DEFAULT_FROM_EMAIL = 'brianobanda08@gmail.com'

# --- AUTHENTICATION AND REDIRECTION SETTINGS ---
# The URL where requests are redirected for login, if required by login_required()
# This should match the 'name' attribute of your login URL pattern in invent/urls.py
LOGIN_URL = 'login' # Changed from '/custom_login/' for consistency with named URL

# The URL to redirect to after a user has successfully logged in.
# This is a fallback. Your custom_login view will handle role-based redirection.
LOGIN_REDIRECT_URL = '/' # Redirect to the root (which is requestor_dashboard in your urls.py)

# The URL to redirect to after a user logs out.
# It's good practice to send them back to the login page.
LOGOUT_REDIRECT_URL = 'login'

# --- SESSION TIMEOUT SETTINGS ---
SESSION_COOKIE_AGE = 600  # <-- 20 minutes (1200 seconds) -->
SESSION_EXPIRE_AT_BROWSER_CLOSE = False # Changed to False for persistent sessions until timeout