# Generated by Django 5.2.3 on 2025-07-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0005_item_category_item_condition_item_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrequest',
            old_name='type',
            new_name='name',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
