# Generated by Django 5.2.3 on 2025-07-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_alter_itemrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.inventoryitem'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
