# Generated by Django 5.2.3 on 2025-07-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0008_alter_itemrequest_item_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(choices=[('Serviceable', 'Serviceable'), ('Not Serviceable', 'Not Serviceable'), ('Not working', 'Not working'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Serviceable', help_text='Current condition of the asset (from Condition in CSV)', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique serial number of the asset (from Serial Number in CSV)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Printer, CPU, Monitor (from Asset Category-Minor)', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(help_text='e.g., Dell Optiplex 7010 (from Asset Description)', max_length=255),
        ),
    ]
