# Generated by Django 5.2.3 on 2025-07-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0009_inventoryitem_condition_inventoryitem_serial_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(choices=[('Serviceable', 'Serviceable'), ('Not Serviceable', 'Not Serviceable'), ('Not working', 'Not working'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Serviceable', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Issued', 'Issued'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='issued_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
