# Generated by Django 5.2.3 on 2025-07-22 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0011_remove_itemrequest_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='date_issued',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='item_request',
            field=models.ForeignKey(blank=True, help_text='Link to the original item request if applicable (for Issue/Return transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='invent.itemrequest'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Issued', 'Issued'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Partially Returned', 'Partially Returned'), ('Fully Returned', 'Fully Returned')], default='Pending', max_length=20),
        ),
    ]
