"""
Django settings for Inventory project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages # Import messages constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v61b8-)9e$s=%%6&+vj6ywju7ko@6g@vzidp(utk)o$9d(3z)='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'users.apps.UsersConfig',   # Custom user app
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # You can add project-wide template directories here if needed, e.g., [BASE_DIR / 'templates']
        'APP_DIRS': True, # This tells Django to look for a "templates" directory inside each installed app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Added debug context processor
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Inventory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Directory where Django will collect all static files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional directories where Django will look for static files
# This is useful for project-level static files not tied to a specific app.
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Example: if you have a 'static' folder directly in your project root
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Custom Authentication Settings ---
# URL to redirect to after a user logs in successfully
LOGIN_REDIRECT_URL = 'users:home' # <--- CHANGED: Use namespaced URL

# URL to redirect to after a user logs out
LOGOUT_REDIRECT_URL = 'users:login_view' # <--- CHANGED: Use namespaced URL

# The URL name for your login page. Used by the @login_required decorator.
LOGIN_URL = 'users:login_view' # <--- CHANGED: Use namespaced URL

# --- Messages Framework Configuration ---
# This allows you to customize the CSS classes for different message levels.
# Useful for styling messages (e.g., success, error) in your templates.
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# --- Email Configuration for Password Reset ---
# For development, use the console backend to print emails to the console.
# This is crucial for testing password reset without a real email server.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # <--- ADDED THIS LINE
# You can optionally set a default from email, though not strictly required for console backend
# DEFAULT_FROM_EMAIL = 'webmaster@yourdomain.com'
