# Generated by Django 5.2.3 on 2025-07-03 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
