# Generated by Django 5.2.3 on 2025-07-08 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_inventoryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Stock', 'In Stock'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=20),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Issue', 'Issue'), ('Adjustment', 'Adjustment'), ('Return', 'Return'), ('Receive', 'Receive')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('issued_to', models.CharField(blank=True, help_text="Recipient for 'Issue' transactions", max_length=255, null=True)),
                ('reason', models.TextField(blank=True, help_text="Reason for 'Adjustment' or 'Return' transactions", null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='invent.inventoryitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
                'permissions': [('can_issue_item', 'Can issue inventory items'), ('can_adjust_stock', 'Can adjust inventory stock'), ('can_receive_stock', 'Can receive new stock into inventory')],
            },
        ),
    ]
