# Generated by Django 5.2.3 on 2025-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0006_rename_type_itemrequest_name_itemrequest_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
